# Generated by Django 4.2.7 on 2023-11-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportapp", "0002_education_home_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="greetings_2",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="home",
            name="picture",
            field=models.ImageField(upload_to="home/"),
        ),
    ]
