# Generated by Django 4.2.7 on 2023-11-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportapp", "0003_alter_home_greetings_2_alter_home_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="greetings_2",
            field=models.CharField(max_length=50),
        ),
    ]
