# Generated by Django 4.2.7 on 2023-11-22 11:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("myportapp", "0006_home_button_icon_home_button_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
