# Generated by Django 4.2.7 on 2023-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportapp", "0007_alter_home_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="description",
            field=models.TextField(default=" ", max_length=300),
        ),
    ]
