# Generated by Django 4.2.7 on 2023-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myportapp",
            "0009_siteconfiguration_author_siteconfiguration_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallinks",
            name="link",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="social_icon",
            field=models.TextField(default=" ", max_length=100),
        ),
    ]
